### ISSUE TITLE
Convert SCB API information to pxweb call

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/pxweb#103]
When we surf pxweb databases we automatically can get the API calles at the homepage.
See: http://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__NV__NV1701__NV1701A/NV1701T12TotAr/table/tableViewLayout1/?rxid=0867ed78-6199-4c29-8040-1e81371aada6

We would like to be able to just put this information in and the pxweb function would fetch this data for us.

**Comment by bjornerstedt** [comment]
I would at least like to see some information on how to incorporate the information in the generated JSON file. For example, I have the JSON code below, generated by SCB. I have tried using `get_pxweb_data()` , but only get the rather uninformative error: 

Error in reorder_and_check_dims(url, dims) : Wrong dims names in call!

Is there a lower level function in pxweb that returns a structure, that I can invoke directly?

```
dimlist <- fromJSON("~/Dropbox/Projects/KKV Project/scb/bnp.json")
gdp <- 
  get_pxweb_data(url = "http://api.scb.se/OV0104/v1/doris/sv/ssd/START/NR/NR0103/NR0103A/NR0103ENS2010T01Kv",
    dims = dimlist$query,
    clean = FALSE)
```

JSON code from SCB:

```
{
"query": [
    {
      "code": "Anvandningstyp",
      "selection": {
        "filter": "item",
        "values": [
          "BNPM",
          "KUTG"
        ]
      }
    },
    {
      "code": "ContentsCode",
      "selection": {
        "filter": "item",
        "values": [
          "NR0103BV"
        ]
      }
    }
  ],
  "response": {
    "format": "xlsx"
  }
}
```

**Comment by MansMeg** [comment]
I've looked into your example and I've written a short parser below. The problem is that these JSON queries do not show everything that is needed to get the data from the API. There is also something that is called ContentCode that describe which type of statistics that is called. If there is only one ContentCode this is not written out by SCB but is needed in the query to SCB. So this will work when ContentCode is written out, otherwise not. I created a fast hack to get the contentCode from the url below as well.

```
parse_json_query <- function(query){
  parsed_query <- RJSONIO::fromJSON(query)
  stopifnot(length(parsed_query) == 2)
  dims <- list()
  for(i in seq_along(parsed_query[[1]])){ 
    dims[[parsed_query[[1]][[i]]$code]] <- parsed_query[[1]][[i]]$selection$values
  }
  dims
}

get_pxweb_contentcode <- function(url){
  metadata <- get_pxweb_metadata(url)
  unlist(lapply(metadata$variables$variables, function(X) if(X$code == "ContentsCode") return(X$values)))
}

```

An example query to work with:
```
query_url <- "http://api.scb.se/OV0104/v1/doris/en/ssd/START/NV/NV1701/NV1701A/NV1701T12TotAr"

query <- '
{
  "query": [
  {
  "code": "Region",
  "selection": {
  "filter": "item",
  "values": [
  "00"
  ]
  }
  },
  {
  "code": "Anlaggning",
  "selection": {
  "filter": "item",
  "values": [
  "S",
  "V"
  ]
  }
  },
  {
  "code": "Tid",
  "selection": {
  "filter": "item",
  "values": [
  "2010",
  "2011",
  "2012"
  ]
  }
  }
  ],
  "response": {
  "format": "px"
  }
  }
'
```


This call do not work:

```
get_pxweb_data(url = query_url, 
               dims = parse_json_query(query))
```

But this does (see the query below):
```
get_pxweb_data(url = query_url, 
               dims = c(parse_json_query(query), ContentsCode = get_pxweb_contentcode(query_url)))
```

It is not pretty but will solve your problem until version 2.0. =)

**Comment by bjornerstedt** [comment]
Thanks, I will look at this. I spent a little time looking at the json
results from SCB with jsonlite. Given my needs, this is where I ended up:

```
library(httr)
indata <- POST(url, body = readChar("~/bnp.json", 500), encode =
"multipart")
writeBin(content(indata, "raw"), "table.xlsx")
```
The json structure of the data is too time consuming at this point, parsing
Excel is so much simpler. With the json file I now have a stable url to the
data at SCB, which is a *huge* improvement on the pre-json download days.


2015-11-10 16:57 GMT+01:00 Måns Magnusson <notifications@github.com>:

**Comment by bubbe** [comment]
In working with JSON and the SCB interface. I have put the url in the JSON input file as follows: 

```
{
  "query": [
...
  ],
  "response": {
        "format": "json-stat"
  },
  "url": "http://api.scb.se/OV0104/v1/doris/sv/ssd/START/NR/NR0103/NR0103A/NR0103ENS2010T01Kv"
}

```
This way I have both parts of a query in the same file. I extract the url using jsonlite and send the whole thing to the SCB server. (It doesn't seem to object to the additional list element.) 

It would be great if the url was automatically included in the json script as indicated above. It can of course also be provided separately as it now is.

**Comment by MansMeg** [comment]
I think this has been fixed now with the new pxweb package.
