### ISSUE TITLE
Change clean to tidy

### ISSUE THREAD

**Issue by bjornerstedt** [rOpenGov/pxweb#104]
Having tested pxweb a little, I find that the output could be improved. In all the cases that I have tried, there are various dimensions  and the last dimension time. It should be said that I have only tried pxweb with the SCB server. Here are some rather specific suggestions:
- I think that the default output should have time as rows and other dimensions as columns. pxweb does the opposite. For example the example in the tutorial on using `get_pxweb_data()` creates a data.frame with one observation of 57 variables (different time periods). 
- The first column should be the time variable as a vector of strings, not rownames. Other columns should be the other dimensions. (In essence this is just the standard SCB output but transposed). 
- Variable names should be the names in the json query (i.e. the values in the filters). With several dimensions, the names can be concatenated with a _ character, for example BNPM_NR0103BW. Basing the variable names on the values in the filter ensures that we get simple unique names.

**Comment by MansMeg** [comment]
Thanks for your suggestions. 

I actually think all your suggestions is solved with the flag ```clean``` set to ```TRUE```. Maybe not the last suggestion, but the labels from SCB is used instead. I think the flag should be renamed to tidy to make a nicer connection to the tidy data theory developed by Hadley Wickham. Now it is actually in a tidy r format when ```clean``` is set to ```TRUE```.

**Comment by thelinkan** [comment]
As the PXweb admin at NIER (konjunkturinstitutet) I thought it would be helpful here with some information on the file format and terminology of PX-files.

In the PX world every "list box" is a variable, and you choose a number of values in each variable.

The variables are grouped into either stub (row variables) and heading (column variables). The norm is to put the time variable as heading, but sometimes it is combined with other variables. These groupings are what is behind the format that is returned from PXWeb. Of course how the R-plugin presents it doesn't necessarily have to be the same way. Each value also has a code, it is this code that is sent to the api to fetch data.

The way we at NIER put together most our files is that we have 4 variables: industry, question, series and time. The combination of the codes for the 3 non-time variable is then the internal series name. Btvi101s is btvi in the industry (manufacturing), 101 is question number and series s is seasonal adjusted. 

What I would like is to be able to recreate these kind of series with this plugin within R.

**Comment by MansMeg** [comment]
@thelinkan, thanks for your suggestion. It would be great if you could put in some example code of your problem.

In general I think the best is to return the data from all pxweb API:s in the "tidy" data format defined in [this](http://www.jstatsoft.org/article/view/v059i10/v59i10.pdf) article. Then anyone can use the tidyr package to expand the dataset or do anything they like with the data to fit your special need. Now using the flag ```clean=TRUE``` should return data in the tidy format - so it is simple to just cast it in any other format of your choice.

**Comment by bjornerstedt** [comment]
It looks better with clean=TRUE as you say. Perhaps you could change the
example code in the tutorial that now has clean=FALSE. I don't understand
why this is not default behaviour, however. If the ambition is to use the
content to reshape the data, having the labels rather than the descriptive
text is really important.

I don't see the point of gathering all the data to long format. When I look
through the actual downloads I have done recently, all are better in wide
format. But other people can of course have other needs. I would prefer an
option there format=LONG in the cases where this is reasonable. It is
better that the default output is in a wide format similar to the Excel
output at SCB, with labels that can easily be used to gather variables, if
necessary.



2015-11-12 17:42 GMT+01:00 Måns Magnusson <notifications@github.com>:

**Comment by MansMeg** [comment]
Thats true. It should be clean as default (it is the default in the function ```get_pxweb_data()```). When we put together a new version we should probably just give the tidyr format as the default.

In genereal it is better to let each package do one thing and not include much data wrangling options. The tidyr tidy data format is a good standard to use. If you have a long (tidyr) format it is just one line of R code to get it to your preferred wide format with the spread function in the tidyr package:
```
tidyr::spread()
```

**Comment by bjornerstedt** [comment]
Tidy data does not mean that _all_ variables should be put in three
columns. It all depends on what the variables of analysis are. Each
variable in the analysis should be a column.

2015-11-12 21:43 GMT+01:00 Måns Magnusson <notifications@github.com>:

**Comment by MansMeg** [comment]
Im not sure but I think thats the tidy data format.

**Comment by bjornerstedt** [comment]
Almost all the examples of tidy tables in the article that you referred to
have many variables. Look for example at Table 10, where the result is a
tidy data set after melting *and casting*, with several variables.

In principle separate works fine, but you don't want to have to separate
everything!

2015-11-12 22:16 GMT+01:00 Måns Magnusson <notifications@github.com>:

**Comment by MansMeg** [comment]
Alright, fix the data format to be tidy it is.

**Comment by MansMeg** [comment]
Hi!

Now I have rewritten the package and hopefully now it is better suited to your needs. It would be great if you could try it out and see if it does what you want it to do:
https://htmlpreview.github.io/?https://github.com/rOpenGov/pxweb/blob/test/vignettes/pxweb.html
