### ISSUE TITLE
New package API

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/pxweb#107]
I'm thinking about trying to straighten up the whole API of the package (and rewrite some to get everything to work properly). I suggest the following package API to use:

`pxweb_get_data(api_url, content, tidy=TRUE)` where contents is a dims list as before or a text string from an SCB json call. Instead of clean we adher to the tidy data format suggested by Hadley Wickham.

`pxweb_interactive(api_url=NULL)`An interactive navigation as before. But now starting with all apis - or a given url/specific API object.

`pxweb_search(api_url=NULL)` Use the search functionality

`pxweb_api_catalogue()` As api_catalogue() before, returns api objects as a list. Prinst less information (only api name and url) - otherwise use summary.

`pxweb_update_api_catalogue()` Updates the api catalogue.

`api_url` takes either an url adress to the api - or an api object return by `pxweb_api_catalogue()`.

Of course everything else will be depricated until version 1.0 - but removed from the documentation index.

I think this should be sufficient for everything. Anyone questions or suggestions? @antagomir @jhuovari @eydunn @thelinkan @tprunarsson

**Comment by antagomir** [comment]
Sounds good to me !

**Comment by MansMeg** [comment]
This is essentially now done.
