### ISSUE TITLE
get_pxweb_data returns message: Error: Success: (200) OK

### ISSUE THREAD

**Issue by AnttiSim** [rOpenGov/pxweb#108]
Something seems to be broken. I get that error message on the title if I run my scripts that have worked correctly before. Error message appears after the message: This is a large query. The data will be downloaded in x batches.

Same thing happens with interactive_pxweb(). I've mainly used Statistics Finland data sets, but I tested other APIs as well and thus far they have given the same error.

**Comment by antagomir** [comment]
Hi, any chance to get one reproducible example of the bug ?

**Comment by AnttiSim** [comment]
For example I tried this:

df <-
  get_pxweb_data(url = "http://pxwebapi2.stat.fi/PXWeb/api/v1/fi/StatFin/vrm/vaerak/055_vaerak_tau_124.px",
             dims = list(Alue = c('*'),
                         Sukupuoli = c('1','2'),
                         Ikä = c('*'),
                         Vuosi = c('*'),
                         Kieli = c('00'),
                         Siviilisääty = c('S')),
             clean = TRUE)

and the output is:

> df <-
+   get_pxweb_data(url = "http://pxwebapi2.stat.fi/PXWeb/api/v1/fi/StatFin/vrm/vaerak/055_vaerak_tau_124.px",
+              dims = list(Alue = c('*'),
+                          Sukupuoli = c('1','2'),
+                          Ikä = c('*'),
+                          Vuosi = c('*'),
+                          Kieli = c('00'),
+                          Siviilisääty = c('S')),
+              clean = TRUE)
This is a large query. The data will be downloaded in 19 batches.
Error: Success: (200) OK

**Comment by AnttiSim** [comment]
And here is session info:

R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252   
[3] LC_MONETARY=Finnish_Finland.1252 LC_NUMERIC=C                    
[5] LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  tcltk     methods  
[8] base     

other attached packages:
[1] pxweb_0.5.57

loaded via a namespace (and not attached):
 [1] httr_1.1.0       compiler_3.2.3   plyr_1.8.3       magrittr_1.5    
 [5] R6_2.1.2         tools_3.2.3      curl_0.9.5       Rcpp_0.12.3     
 [9] RJSONIO_1.3-0    stringi_1.0-1    data.table_1.9.6 jsonlite_0.9.19 
[13] stringr_1.0.0    chron_2.3-47

**Comment by MansMeg** [comment]
Hmm... I wonder if this can be a problem with httr. Can you run '''sessionInfo()'''?


Skickat från min iPhone

**Comment by AnttiSim** [comment]
@MansMeg Yes, I just did.

**Comment by AnttiSim** [comment]
Were you able to confirm this? Was it the new httr version?

**Comment by MansMeg** [comment]
It seems to be that httr 1.1 is not backwards compatible with status messages. I have fixed this and pushed a new version (0.6.0) to the development branch. You can install it with: 
```devtools::install_github("rOpenGov/pxweb", ref="development")```

**Comment by AnttiSim** [comment]
Thanks! It works again.
