### ISSUE TITLE
update_pxweb_apis() - Error

### ISSUE THREAD

**Issue by eydunn** [rOpenGov/pxweb#114]
> update_pxweb_apis()
> Error in simplify(obj, simplifyVector = simplifyVector, simplifyDataFrame = simplifyDataFrame,  : 
>   unused argument (encoding = NULL)

See: https://github.com/hadley/httr/issues/330#issuecomment-200806857

**Comment by MansMeg** [comment]
Hmm. Thanks. Maybe we should wait for the fix in the httr package?

**Comment by MansMeg** [comment]
This is now fixed with the new pxweb api package
