### ISSUE TITLE
package ‘pxweb’ is not available (for R version 3.3.0)

### ISSUE THREAD

**Issue by eydunn** [rOpenGov/pxweb#116]
Hi,

I just installed R version 3.3.0 - and then I noticed that the pxweb package disappeared :-(

Is there some incompatibility with the newest R version?

> Warning in install.packages : 
> package ‘pxweb’ is not available (for R version 3.3.0)

**Comment by antagomir** [comment]
This is unintentional. We need to fix the issue. Meanwhile, you can always load the latest development version with:

```
library(devtools)
install_github("ropengov/pxweb")
```

Sorry for the inconvenience.


The CRAN page now says:

Package ‘pxweb’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2016-05-02 as check problems were not corrected despite reminders. 

I have not seen these reminders, need to find out where they have gone.

**Comment by MansMeg** [comment]
Im looking into this. There is multiple problems right now, both incombatible issues with new testthat package and some issues with 3.3.0.

**Comment by MansMeg** [comment]
It is now submitted to CRAN aiagn (version 0.6.3). I skipped some test that was strange so the coverage went down to 60% instead of 73 percent but this will be fixed with the new API.

**Comment by MansMeg** [comment]
On CRAN now. Thanks for the information!

**Comment by eydunn** [comment]
Great! Thank you. :-)
