### ISSUE TITLE
option to download latest periods

### ISSUE THREAD

**Issue by captHaddock** [rOpenGov/pxweb#118]
On webpages/databases that uses px-web, users have the option to:
"Update the search with a rolling start time point and an unchanged number of time periods".

It would be nice to have a similar option in the api-call function in this package.

**Comment by MansMeg** [comment]
Hi! Sorry for delayed response. Im currently rewriteing the package and then this will be possible.

**Comment by MansMeg** [comment]
Hi!

Now the package is rewritten and you can specify this in a json query to the API. See the vignette:
https://htmlpreview.github.io/?https://github.com/rOpenGov/pxweb/blob/test/vignettes/pxweb.html

Hope this gives you what you want.
