### ISSUE TITLE
Replace RJSONIO with jsonlite

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/pxweb#119]
The [rOpenSci guidelines](https://github.com/ropensci/packaging_guide) suggest: "For parsing JSON, use jsonlite instead of rjson or RJSONIO."

**Comment by olangsrud** [comment]
Another point is that jsonlite is a part of https://cran.r-project.org/package=tidyverse which seems to be an accepted standard.

**Comment by MansMeg** [comment]
Yes. When the new engine is up, the only dependencies will be jsonlite, httr and checkmate.

**Comment by MansMeg** [comment]
This is now done.
