### ISSUE TITLE
Add API 

### ISSUE THREAD

**Issue by GitHubFriendly** [rOpenGov/pxweb#120]
Hi! Can we add the pxweb_databases of Statistics and research Åland? It should be configurated the same way as Statistics Finland. It is part of the www.stat2go.com website that was mentioned in an earlier post here, so I think it should be good to go as long as its added in the package pxweb? Im very new to R though, so I'm not sure.

**Comment by antagomir** [comment]
Yes this would be great. 

Could you add the necessary urls etc in the pxweb R package, test it, and send us a pull request ? 

Potentially we could also do that ourselves but this might take for a longer time.

**Comment by GitHubFriendly** [comment]
I will try to find the information you need straight away! Im sorry to say I barely have any R experience so I dont think Im able to help with the coding that much.

**Comment by GitHubFriendly** [comment]
url=pxweb.asub.ax 
version=v.1
languages=sv, en
limit=same as statistics finland I would guess.
url template= pxweb.asub.ax/PXWeb/api/[version]/[lang]

I think this is the correct information.

**Comment by antagomir** [comment]
In principle the URL to the database is sufficient, but that has to be
added it to the selection and documentation as well.

**Comment by MansMeg** [comment]
It has been added to the api catalogue now. Thanks!
