### ISSUE TITLE
How can I see the updated api_catalogue?

### ISSUE THREAD

**Issue by GitHubFriendly** [rOpenGov/pxweb#121]
Hi! Thank you very much for adding ÅSUB to the api_catalogue! I wanted to try it now but it is not in the catalogue whene I´m running R. I tried updating packages but R said all my packages are up to date. Does anyone know if I´m missing something and how I can access the added database?

**Comment by antagomir** [comment]
Did you reinstall it from the CRAN release version (with the install.packages())? The update is so far only available in the Github development version. Use devtools::install_github("ropengov/pxweb") for that.

I also updated the version number.

**Comment by GitHubFriendly** [comment]
Thanks! Now I can access it. I tested the ÅSUB api and I could download data and use the interactive_pxweb. However in the first list in the interactive web, where one has to choose which ÅSUB database that one wants to explore, some of the databases (numbers 1,5,6,10,11) dont work, and produce this errormessage: "Error in `$<-.data.frame`(`*tmp*`, "text", value = character(0)) : 
  replacement has 0 rows, data has 1"

Maybe this is a problem we can try to fix in ÅSUB, but it seems strange when the www.stat2go.com can access all ÅSUB-databases.

**Comment by MansMeg** [comment]
Hmm. I need to look this up. Do you know if you can access this directly by downloading the data through `get_pxweb_data()` or is it only the interactive approach that do not work properly?

**Comment by GitHubFriendly** [comment]
It works to download directly via get_pxweb_data, as far as I can see its only the interactive_pxweb that doesnt work properly

**Comment by eydunn** [comment]
Hi, I'm seeing the same thing in an internal 'sandbox'-site. And it is only in interactive_pxweb(). We first encountered this approximately one week ago. At the time we didn't have time to investigate it further.

**Comment by MansMeg** [comment]
Alright. Ill look into it.

**Comment by MansMeg** [comment]
It is not possible to use this functionality any more due to CRAN policy. So I'm going to write a short tuturial on how to do this manually. 

Allthough, with the new pxweb package you can navigate any pxweb api as long as you have a pth to any position in the API. See:
https://htmlpreview.github.io/?https://github.com/rOpenGov/pxweb/blob/test/vignettes/pxweb.html
