### ISSUE TITLE
visitfinland to be added into API catalog

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/pxweb#122]
Received request to add http://visitfinland.stat.fi/PXWeb/pxweb/fi/VisitFinland to pxweb api catalog.

**Comment by antagomir** [comment]
Adding the info in inst/extdata/api.json led to some errors. To investigate later.


  Running ‘testthat_pxweb_api_class.R’
 ERROR
Running the tests in ‘tests/testthat_pxweb_api_class.R’ failed.
Last 13 lines of output:
  1. Failure: pxweb_api_class (@test-pxweb_api_class.R#76) -----------------------
  NOT({
      ...
  } did not throw an error.
  )

**Comment by MansMeg** [comment]
I tried to find a path to a pxweb api, but did not succeed? Do you have contacts at Visit Finland and could check if the have the api enabled?

**Comment by antagomir** [comment]
I have now contacted they person who initially requested this. I could not find this either. So let us wait and see.

**Comment by MansMeg** [comment]
Any news here @antagomir ?

**Comment by antagomir** [comment]
Unfortunately no reply. I will ask again, assuming that http://visitfinland.stat.fi/PXWeb/pxweb/fi/VisitFinland has been tested (see above) and does not work as API.

**Comment by MansMeg** [comment]
Yes. I tried to find an API path, but it seemed like they do not have the API enabled, only the home page.

**Comment by antagomir** [comment]
Ok I have asked again.

**Comment by antagomir** [comment]
I now received answer from visitfinland.

The direct API-link to "Tilastopalvelu Rudolf" (statistics service "Rudolf") http://visitfinland.stat.fi/PXWeb/api/v1/fi/VisitFinland

Further info in Finnish below:

    Aineistolistaus: Tilastotietokanta Rudolf

    Kieli: suomi/englanti

    Data päivitetty: jatkuvapäivitteinen

    Taulukkotiedostojen natiiviformaatti: PC-Axis (.px)

    Muut käytettävissä olevat tiedostomuodot: XLSX, XML, JSON, JSON-stat, CSV, jne.

    Linkki käyttöliittymään: http://visitfinland.stat.fi/PXWeb/pxweb/fi/VisitFinland

    Tekninen tuki: tietokannat@stat.fi

    Lisenssi: CC BY 4.0

 

Tilastopalvelu Rudolfin API-rajapinta

 

    Dokumentaatio: http://pxnet2.stat.fi/api1.html

    API-linkki: http://visitfinland.stat.fi/PXWeb/api/v1/fi/VisitFinland

    Kannan rakenne: http://visitfinland.stat.fi/pxweb/api/v1/fi/VisitFinland/?query=*&filter=*

**Comment by antagomir** [comment]
PR created. Should be fixed now. I tested the new catalog and it seemed to work. CRAN build/checks ok.
