### ISSUE TITLE
API JSON catalog location

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/pxweb#123]
Is there a reason that the API catalog is retrieved from github (https://raw.githubusercontent.com/rOpenGov/pxweb/master/inst/extdata/api.json) in the file R/api_catalogue.R - we could as well keep it in the package itself and call from there. I can make this change if you agree but hesitant otherwise. Ping @MansMeg

**Comment by MansMeg** [comment]
You can fix it. I think it was a smart idea me or Love had so people do not need to update the whole package to get the latest apis. But I guess it would be smarter to have the api catalogue as a part of the package.

**Comment by antagomir** [comment]
Ok, done.
