### ISSUE TITLE
Choosing between values and code

### ISSUE THREAD

**Issue by thelinkan** [rOpenGov/pxweb#125]
When I download a dataset via get_pxweb_data I get the full values of the choices I have made. In the code to download the data I insert the codes for the choices

eg.

    testpx <- 
      get_pxweb_data(url = "http://statistik.konj.se/PXWeb/api/v1/sv/KonjBar/ftgmanad/Barboam.px",
                 dims = list("Bransch (SNI 2007)" = c('TOTF', 'BBOA'),
                             Fråga = c('101', '102'),
                             Serie = c('O', 'S'),
                             Period = c( '2016M11', '2016M12', '2017M01', '2017M02')),
                 clean = TRUE)

I would like an option to get these codes in the downloaded data instead of the full text.
Right now I get this:

              Bransch (SNI 2007)                 Fråga                      Serie  Period values
    1        Byggindustri (41-43)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2016M11     33
    2        Byggindustri (41-43)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2016M12     35
    3        Byggindustri (41-43)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2017M01     27
    4        Byggindustri (41-43)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2017M02     34
    5        Byggindustri (41-43)    Byggandet (utfall)    Nettotal: Säsongsrensat 2016M11     33
    6        Byggindustri (41-43)    Byggandet (utfall)    Nettotal: Säsongsrensat 2016M12     40
    7        Byggindustri (41-43)    Byggandet (utfall)    Nettotal: Säsongsrensat 2017M01     39
    8        Byggindustri (41-43)    Byggandet (utfall)    Nettotal: Säsongsrensat 2017M02     42
    9        Byggindustri (41-43) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2016M11      5
    10       Byggindustri (41-43) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2016M12      6
    11       Byggindustri (41-43) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2017M01      4
    12       Byggindustri (41-43) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2017M02      8
    13       Byggindustri (41-43) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2016M11      8
    14       Byggindustri (41-43) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2016M12     11
    15       Byggindustri (41-43) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2017M01     10
    16       Byggindustri (41-43) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2017M02     10
    17 Bygg- & anläggning (41+42)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2016M11     34
    18 Bygg- & anläggning (41+42)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2016M12     32
    19 Bygg- & anläggning (41+42)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2017M01     20
    20 Bygg- & anläggning (41+42)    Byggandet (utfall) Nettotal: Ej Säsongsrensat 2017M02     41
    21 Bygg- & anläggning (41+42)    Byggandet (utfall)    Nettotal: Säsongsrensat 2016M11     37
    22 Bygg- & anläggning (41+42)    Byggandet (utfall)    Nettotal: Säsongsrensat 2016M12     44
    23 Bygg- & anläggning (41+42)    Byggandet (utfall)    Nettotal: Säsongsrensat 2017M01     39
    24 Bygg- & anläggning (41+42)    Byggandet (utfall)    Nettotal: Säsongsrensat 2017M02     39
    25 Bygg- & anläggning (41+42) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2016M11      9
    26 Bygg- & anläggning (41+42) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2016M12     11
    27 Bygg- & anläggning (41+42) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2017M01     11
    28 Bygg- & anläggning (41+42) Anbudspriser (utfall) Nettotal: Ej Säsongsrensat 2017M02      9
    29 Bygg- & anläggning (41+42) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2016M11     13
    30 Bygg- & anläggning (41+42) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2016M12     15
    31 Bygg- & anläggning (41+42) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2017M01     12
    32 Bygg- & anläggning (41+42) Anbudspriser (utfall)    Nettotal: Säsongsrensat 2017M02     10

I want this

        Bransch (SNI 2007)    Fråga    Serie   Period   values
    1        TOTF              101       o     2016M11     33
    2        TOTF              101       o     2016M12     35
    3        TOTF              101       o     2017M01     27
    4        TOTF              101       o     2017M02     34
    5        TOTF              101       s     2016M11     33
    6        TOTF              101       s     2016M12     40
    7        TOTF              101       s     2017M01     39
    8        TOTF              101       s     2017M02     42
    9        TOTF              102       o     2016M11      5
    10       TOTF              102       o     2016M12      6
    11       TOTF              102       o     2017M01      4
    12       TOTF              102       o     2017M02      8
    13       TOTF              102       s     2016M11      8
    14       TOTF              102       s     2016M12     11
    15       TOTF              102       s     2017M01     10
    16       TOTF              102       s     2017M02     10
    17       BBOA              101       o     2016M11     34
    18       BBOA              101       o     2016M12     32
    19       BBOA              101       o     2017M01     20
    20       BBOA              101       o     2017M02     41
    21       BBOA              101       s     2016M11     37
    22       BBOA              101       s     2016M12     44
    23       BBOA              101       s     2017M01     39
    24       BBOA              101       s     2017M02     39
    25       BBOA              102       o     2016M11      9
    26       BBOA              102       o     2016M12     11
    27       BBOA              102       o     2017M01     11
    28       BBOA              102       o     2017M02      9
    29       BBOA              102       s     2016M11     13
    30       BBOA              102       s     2016M12     15
    31       BBOA              102       s     2017M01     12
    32       BBOA              102       s     2017M02     10

**Comment by MansMeg** [comment]
Thanks. Ill add this as a feature request.

**Comment by captHaddock** [comment]
Also interested in this! Would make it easier to join on data from other sources.

**Comment by MansMeg** [comment]
Great! I have now rewritten the package totally and now this should be straight-forward. Just check the new vignette here:
https://htmlpreview.github.io/?https://github.com/rOpenGov/pxweb/blob/test/vignettes/pxweb.html

It is now much more simple to build upon the package for others.
