### ISSUE TITLE
Problems downloading data having a long list (>100,000) of selections

### ISSUE THREAD

**Issue by hoehleatsu** [rOpenGov/pxweb#127]
Dear package maintainers,

thanks for this very helpful package. I've successfully downloaded data from SCB, which otherwise would have been very painful to download by hand. However, when I direct the package to the SCB dataset entitled BE0001ENamn10, I'm running into problems (see log below). My suspicion is that the list of last names (=efternamn) is too long as it contains more than 100,000 observations, but I'm not sure. Compare also with the manual way to get to the data: http://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__BE__BE0001/BE0001ENamn10/?rxid=7ea7f786-b6a8-4369-83c8-e529a47285b1

Any ideas what's causing this?

Best regards,
Michael
> d <- interactive_pxweb(api = "api.scb.se", version = "v1", lang = "en")
Content of 'api.scb.se' at current (1) node level:
========================================================================
1.  [BE] Population
2.  [EN] Energy
3.  [HA] Trade in goods and services
4.  [JO] Agriculture, forestry and fishery
5.  [ME] Democracy
6.  [NR] National accounts
7.  [OE] Public finances
8.  [TK] Transport and communications
9.  [AM] Labour market
10. [BO] Housing, construction and building
11. [FM] Financial markets
12. [HE] Household finances
13. [LE] Living conditions
14. [MI] Environment
15. [NV] Business activities
16. [PR] Prices and Consumption
17. [UF] Education and research

Enter the data (number) you want to explore:
('esc' = Quit, 'b' = Back) 
1: 1
Content of 'api.scb.se' at current (2) node level:
========================================================================
1. [BE0701] Demographic Analysis (Demography)
2. [BE0001] Name statistics
3. [BE0401] Population projections
4. [BE0101] Population statistics

Enter the data (number) you want to explore:
('esc' = Quit, 'b' = Back) 
1: 2
Content of 'api.scb.se' at current (3) node level:
========================================================================
1.  [BE0001T04Ar]   Newborns, first names normally used with at least 10 newborns with the same name, by year. Year 1998 -
                    2016
2.  [BE0001T04BAr]  Newborns, first names normally used with at least 2 newborns with the same name. Year 2004 -
                    2016
3.  [BE0001T05AR]   Newborns, the 10 and 100 most common first names normally used, by year. Year 1998 -
                    2016
4.  [BE0001T06AR]   First names normally used, the 10 and 100 most common among persons registered on 31 December of each year. Year 1999 -
                    2016
5.  [BE0001T03Ar]   Last names, the 10 and 100 most common last names among persons registered on 31 December of each year. Year 1980 -
                    2016
6.  [BE0001T07AR]   First names, the 10 and 100 most common among persons registered on 31 December of each year. Year 1980 -
                    2016
7.  [BE0001T08AR]   First names normally used by average age among persons registered on 31 December of each year. Year 2005 -
                    2016
8.  [BE0001F100]    First names, the 100 most common for women and men 31 December 2016. Year of birth 1917 -
                    2016
9.  [BE0001T100]    First names normally used, the 100 most common  for women and men 31 December 2016. Year of birth 1916 -
                    2016
10. [BE0001ENamn10] Last names with at least 10 bearers among persons registered on 31 December of each year. Year 1999 -
                    2016
11. [BE0001TNamn10] First names normally used with at least 10 bearers among persons registered on 31 December of each year. Year 1999 -
                    2016
12. [BE0001FNamn10] First names with at least 10 bearers among persons registered on 31 December of each year. Year 1999 -
                    2016

Enter the data (number) you want to explore:
('esc' = Quit, 'b' = Back) 
1: 10
Do you want to download 'http://api.scb.se/OV0104/v1/doris/en/ssd/BE/BE0001/BE0001ENamn10'?
('esc' = Quit, 'y' = Yes, 'n' = No) 
1: y
Do you want to clean and melt this file (to wide R format)?
('esc' = Quit, 'y' = Yes, 'n' = No) 
1: y
Do you want to print the code for downloading this data?
('esc' = Quit, 'y' = Yes, 'n' = No) 
1: y
Error in listElem$values : $ operator is invalid for atomic vectors
>

**Comment by MansMeg** [comment]
Thanks! Ill look into this. As you say it is probably that. Im vurrently rewriting the package so Ill try to fix it.

**Comment by hoehleatsu** [comment]
Thx, it looks like the REST interface doesn't return the set of values. At least when I call http://api.scb.se/OV0104/v1/doris/en/ssd/BE/BE0001/BE0001ENamn10 I only get:

{"title":"Last names by last names, observations and year","variables":[{"code":"Efternamn","text":"last names"},{"code":"ContentsCode","text":"observations","values":["BE0001AK"],"valueTexts":["Last names"]},{"code":"Tid","text":"year","values":["1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016"],"valueTexts":["1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016"],"time":true}]}

(not sure this is helpful). Otherwise thx for a great package, it saved me lots of time when trying to download some first name data.

**Comment by MansMeg** [comment]
Yes, that can be the reason. It seems to be something wrong with the SCB API from the looks of it? Why would you otherwise not have any data?

**Comment by MansMeg** [comment]
I have now rewritten the whole pxweb package and I hoped I would fix this. By I get a 403 forbidden error, so I need to contact SCB to fix this. Thansk for submitting the bug.

**Comment by MansMeg** [comment]
The 403 Forbidden is a bug in SCB API (two different limits). See #168 .
