### ISSUE TITLE
Internet connection fails - broken dependency?

### ISSUE THREAD

**Issue by AnttiSim** [rOpenGov/pxweb#128]
Hi,

I got an error message by trying to connect to Statistics Finland API (with get_pxweb_data):

Error: No internet connection to http://pxnet2.stat.fi/PXWeb/api/v1/fi/StatFin/jul/jtume/010_jtume_tau_101.px

This error appears after the programs issues that "This is a large query...". I attach here files that should help you to reproduce the problem.

[errorPxweb.zip](https://github.com/rOpenGov/pxweb/files/871741/errorPxweb.zip)

I'm thinking that when I did package update this morning, some update caused this trouble. I had some earlier session on without updated packages that runs the script faultlessly. Here is session info of the failed download:

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252   
[3] LC_MONETARY=Finnish_Finland.1252 LC_NUMERIC=C                    
[5] LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  tcltk     methods  
[8] base     

other attached packages:
[1] pxweb_0.6.3

loaded via a namespace (and not attached):
 [1] httr_1.2.1        plyr_1.8.4        magrittr_1.5      R6_2.2.0         
 [5] tools_3.3.3       Rcpp_0.12.10      RJSONIO_1.3-0     stringi_1.1.3    
 [9] data.table_1.10.4 stringr_1.2.0    

Cheers,

Antti

**Comment by MansMeg** [comment]
Thanks! Ill look into it when I have the time.

**Comment by AnttiSim** [comment]
I have my routine working again. It seems that package 'curl' got somehow uninstalled when I updated R to 3.3.3. I installed 'curl' again and now everything works as it should. So this was probably just a false alarm. Apologies for that!

Kind regards,

Antti
