### ISSUE TITLE
Separate region code and region name in SCB data

### ISSUE THREAD

**Issue by filipwastberg** [rOpenGov/pxweb#129]
When downloading data from the SCB API you get a region column with both the region code and the region name. 

It would be preferable to have them separated. I use the following code in order to separate them. Maybe something like it can be added when downloading from SCB?

```
library(dplyr)
library(stringr)

data %>%
mutate(region_code = as.numeric(str_extract(region, "([0-9]{4})")),
       region_name = str_extract(region, "[aA-öÖ].+")) %>%
select(-region)
```

**Comment by MansMeg** [comment]
Thanks. I'm rewriting the package so I can have it in consideration. But I want to have as little processing in the pxweb package as possible. The package should do one thing (search and download data from pxweb apis) and do that good. Data munging is, as you show, best done using tidyr and dplyr.
