### ISSUE TITLE
add prognos.konj.se

### ISSUE THREAD

**Issue by andcarl** [rOpenGov/pxweb#132]
In the api.json-file there is an alias "konj" for konjunkturinstitutet that works fine, the url is statistik.konj.se. I would like to ask you to also add another alias that corresponds to the url prognoser.konj.se/. I tried to change the api.json-file to this (just copying the information for the alias "konj") and it seems to work fine:

....
"statistik.konj.se": {
        "alias" : ["konjstatistik"],
        "description" : "The Swedish national institute of economic research",
        "url" : "http://statistik.konj.se/PXWeb/api/[version]/[lang]",
        "version": ["v1"], 
        "lang": ["en", "sv"],
        "calls_per_period": 30,
        "period_in_seconds": 1,
        "max_values_to_download" : 10000
              },
    
    "prognos.konj.se": {
        "alias" : ["konjprognos"],
        "description" : "The Swedish national institute of economic research",
        "url" : "http://prognos.konj.se/PXWeb/api/[version]/[lang]",
        "version": ["v1"], 
        "lang": ["en", "sv"],
        "calls_per_period": 30,
        "period_in_seconds": 1,
        "max_values_to_download" : 10000
              },
....

**Comment by MansMeg** [comment]
Great! Can you try to add this as a pull request?

**Comment by andcarl** [comment]
I'm new on git/github but I've managed to clone the master branch. It now seems that it's already been added to the api.json file.

**Comment by MansMeg** [comment]
Ok? And it does not work?

**Comment by andcarl** [comment]
It looks like exactly the thing I'm after. However, I haven't succeded in installing/running packages from Github so I can't say that I've tried running it. I'm sure it's fine, I'll wait and get a new version from CRAN. Thank you!

**Comment by MansMeg** [comment]
Hi!

It should work to just use:
```
install.packages("devtools")
devtools::install_github("rOpenGov/pxweb")
```

**Comment by andcarl** [comment]
I just tried it on my personal laptop (at work the firewall seems to block the github installation) and it worked, and I was able to reach the prognosis database of konjunkturinstitutet. Thanks again!

**Comment by MansMeg** [comment]
Great! If you want it at work you can download it as a zip, unpack it and use:

```
devtools::install_local("[path to the unziped (or maybe the ziped work as well) package]")
```

I close this issue now.

/Måns
