### ISSUE TITLE
package rjstat

### ISSUE THREAD

**Issue by janbrus** [rOpenGov/pxweb#133]
Just a comment for your information. 
PX-web supports the output format [JSON-Stat](https://json-stat.org). JSON-Stat is a format made for statistical tables (mulidimensional datasets). The R package [rjstat](https://cran.r-project.org/web/packages/rjstat/index.html) is for reading and writing JSON-Stat datasets. 

Jan Bruusgaard, Statstistics Norway

**Comment by janbrus** [comment]
There are two small examples here: http://www.ssb.no/en/omssb/tjenester-og-verktoy/api/px-api/code-examples.
Eurostat's API, which is not pxweb, also supports JSON-Stat.

**Comment by antagomir** [comment]
Perfect. We should also note this with the eurostat R package.

**Comment by MansMeg** [comment]
Great. Now the pxweb package support returning json-stat.
