### ISSUE TITLE
Error in listElem$values : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by magnusmki** [rOpenGov/pxweb#134]
When trying to retrieve data from Statice (px.hagstofa.is), this error is thrown for quite many tables, but not all of them:

> Error in listElem$values : $ operator is invalid for atomic vectors

The error can be created, for this table, for example:

>  d=interactive_pxweb()
>  1:   10. [px.hagstofa.is] Statistics Iceland
>  1:   1 [1] is
>  1:   2 [2] Efnahagur
>  1:   4 [utanrikisverslun]    Utanríkisverslun
>  1:   1 [1_voruvidskipti] Vöruviðskipti
>  1:   2 [02_uttollskra]          Tollskrárnúmer - útflutningur
>  1:   1  [UTA02801.px] Útflutningur eftir tollskrárnúmerum 2016-2017, kafli 1-40
>  1:   y
>  1:   y
>  1:   n

Kind regards
MK

**Comment by magnusmki** [comment]
Another issue i ran intu, while using interactive_pxweb() was: 

Error in batches$dims[[batch_no]][[dimNames[i]]] : 
  attempt to select less than one element in get1index

**Comment by MansMeg** [comment]
Thank you! I have the intention to fix this this spring by doing a rewrite of the package.

Måns

**Comment by MansMeg** [comment]
This has now been fixed with the new pxweb package, Thanks for the issue!
