### ISSUE TITLE
get footnotes

### ISSUE THREAD

**Issue by GitHubFriendly** [rOpenGov/pxweb#137]
The tables´ footnotes should be part of the pxweb metadata, but I cant seem to get it with the get_pxweb_metadata commando. Is there any solution that I´m missing?

**Comment by MansMeg** [comment]
Thank you! Good suggestion!

**Comment by GitHubFriendly** [comment]
Thanks. And thanks again for a brilliant package, it is really useful!

**Comment by MansMeg** [comment]
Hi!

The package is now rewritten so now you can get these footnotes easily. See the new vignette/tuturial here:

https://htmlpreview.github.io/?https://github.com/rOpenGov/pxweb/blob/test/vignettes/pxweb.html
