### ISSUE TITLE
When a mix node have be found

### ISSUE THREAD

**Issue by silvia-rguez** [rOpenGov/pxweb#139]
Hi,

I am using the pxweb R-package in a program that:
- Goes down through all the Grønlands Statistik [stat-bank](bank.stat.gl) nodes, 
- Finds the table nodes's URL
- Keeps the tables URL in a list
- Retrieves some metadata
- and writes a csv file for each table.

When I run the program, the nodes that mix "l" nodes and "t" nodes issues an error, makes the program stop for long time and it doesn't go further. An example of what I mean with «mix "l" nodes and "t" nodes» on the URL below

[http://bank.stat.gl/api/v1/en/Greenland/BE/BE01](http://bank.stat.gl/api/v1/en/Greenland/BE/BE01)

Here is the get_pxweb_metadata() function output in the 3 different cases:

```
**Node with tables only** ---
get_pxweb_metadata(baseURL="http://bank.stat.gl/api/v1/en/Greenland/BE/BE80")

           id type                                            text             updated                                                          URL
1  BEXCALC.PX    t           Population account <em>[BEECALC]</em> 2017-02-09T05:52:02   http://bank.stat.gl/api/v1/en/Greenland/BE/BE80/BEXCALC.PX
2 bexcalcr.px    t Regional population account <em>[BEECALCR]</em> 2018-05-09T09:01:33  http://bank.stat.gl/api/v1/en/Greenland/BE/BE80/bexcalcr.px
3 BEXFERTR.px    t                    Liveborn <em>[BEEFERTR]</em> 2018-05-04T04:38:37  http://bank.stat.gl/api/v1/en/Greenland/BE/BE80/BEXFERTR.px


**Node with nodes only** ---
get_pxweb_metadata(baseURL="http://bank.stat.gl/api/v1/en/Greenland/BE")

    id type                    text                                             URL
1 BE80    l                Analysis http://bank.stat.gl/api/v1/en/Greenland/BE/BE80
2 BE99    l                Archieve http://bank.stat.gl/api/v1/en/Greenland/BE/BE99
3 BE60    l              Households http://bank.stat.gl/api/v1/en/Greenland/BE/BE60
4 BE01    l Population in Greenland http://bank.stat.gl/api/v1/en/Greenland/BE/BE01
5 BE85    l    Quarterly Population http://bank.stat.gl/api/v1/en/Greenland/BE/BE85
6 BE10    l        Vital Statistics http://bank.stat.gl/api/v1/en/Greenland/BE/BE10


**Node with both node types**---
get_pxweb_metadata(baseURL="http://bank.stat.gl/api/v1/en/Greenland/BE/BE01")
                                                                                                 X1                   X2
1 BEXSAT1.px, t, Population and population growth 1901-2017 <em>[BEESAT1]</em>, 2017-02-07T10:26:25 BE0150, l, Forecasts
                       X3                             X4                                             URL
1 BE0120, l, January 1.st BE0140, l, Midyear (July 1.st) http://bank.stat.gl/api/v1/en/Greenland/BE/BE01
```
In order to solve this problem I have tried to transform the structure retrieved in the mix-nodes into an structure that looks like the non mix-nodes. 

My questions are:

- How should I create that structure? 
- Is there any specific object type I have to use?.
- Does the pxweb package have a way to create it?

Thank you in advance
sIrO

**Comment by MansMeg** [comment]
Thank you for your well dexcribed example. Unfortunately I have not fast or easy answer to your question.

**Comment by silvia-rguez** [comment]
Ok, thank you.

**Comment by MansMeg** [comment]
Hi!

I'm currently rewriting the package and now your problem has been fixed. The structure is somewhat different but it should work for your purposes I guess. The new package has not been released but all tests pass so you could use it already, even though you need to install it from the test branch. Thanks again for submitting an issue!

```
> devtools::install_github('ropengov/pxweb', ref = "test")
> library(pxweb)
> url <- "http://bank.stat.gl/api/v1/en/Greenland/BE/BE01"
> px_meta_data <- pxweb_get(url)
> px_meta_data
PXWEB LEVELS
  BEXSAT1.px (t): Population and population growth 1901-2017 <em>[BEESAT1]</em>
  BE0150 (l): Forecasts
  BE0120 (l): January 1.st
  BE0140 (l): Midyear (July 1.st)
```
