### ISSUE TITLE
API -list update

### ISSUE THREAD

**Issue by janbrus** [rOpenGov/pxweb#140]
Here is an update, last 4 lines, about Statstics Norway  /pxweb/blob/master/inst/extdata/api.json.  

    "data.ssb.no": { 
        "alias" : ["ssb"],
        "description" : "Statistics Norway",
        "url" : "http://data.ssb.no/api/[version]/[lang]",
        "version": ["v0"], 
        "lang": ["en","no"],
        "calls_per_period": 30,
        "period_in_seconds": 60,
        "max_values_to_download" : 500000
    },

**Comment by antagomir** [comment]
Thanks , added !

**Comment by janbrus** [comment]
Sorry, I ment that you should correct the existing entry, not add a new. Now it is twice. Please remove the old entry.
