### ISSUE TITLE
Info: R package PxWebApiData

### ISSUE THREAD

**Issue by janbrus** [rOpenGov/pxweb#141]
I just want to inform about PxWebApiData: PX-Web Data by API
https://CRAN.R-project.org/package=PxWebApiData

Function to read PX-Web data into R via API. The example code reads data from the three national statistical institutes, Statistics Norway, Statistics Sweden and Statistics Finland.

**Comment by MansMeg** [comment]
Cool. It seems like you are one of the developers. What do you say about joining forces on one package instead?
