### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/pxweb#153]
The current set of tests use deprecated functions (see output of devtools::test()) and should be updated.

**Comment by antagomir** [comment]
Not sure if all the R files in the tests/ directory are needed. 

It might be enough to have a single test file that runs through all tests from the testthat subfolder. 

This is simpler and works at least for [eurostat](https://github.com/rOpenGov/eurostat/tree/master/tests).

**Comment by antagomir** [comment]
I replaced the individual R files in the tests/ folder with a single R file that runs through all test files at once.

**Comment by MansMeg** [comment]
Now fixed
