### ISSUE TITLE
backwards compability

### ISSUE THREAD

**Issue by arhot** [rOpenGov/pxweb#166]
I understand the need for updating the package, but for an API package it would be useful to note somewhere whether the API itself has changed or just the package, if backwards compatibility is not possible.

I.e. my old code worked by downgrading the package, but I'm not sure if this will cease to be the case when Statistics Finland updates their interface.

**Comment by MansMeg** [comment]
Did not the package work with your code? It should be perfectly back compatible, but just theowing warnings?

**Comment by MansMeg** [comment]
To be clear. My intention is to make full backward compatability as much as possible. Old functions are deprecated and will not be maintained, but they will not be removed for at least a year.

**Comment by arhot** [comment]
Actually, yes, nevermind, it works. The problem was elsewhere. Thanks and sorry to bother you!
