### ISSUE TITLE
Pxweb 0.8.3 doesn't handle large queries

### ISSUE THREAD

**Issue by christianlindell** [rOpenGov/pxweb#168]
I don't know if SCB handle querries different if the return format is json instead of text or if this is a bug:

In the previous version of pxweb, this code worked:

```
library(pxweb) # previous version

myDataSetName <-
    get_pxweb_data(url = "http://api.scb.se/OV0104/v1/doris/sv/ssd/BE/BE0101/BE0101A/BefolkningNy",
                   dims = list(Region = c('*'),
                               Civilstand = c('*'),
                               Alder = c('*'),
                               Kon = c('*'),
                               ContentsCode = c('BE0101N1'),
                               Tid = c('2017')),
                   clean = TRUE)
```
Output:

This is a large query. The data will be downloaded in 3 batches. ... Download done.

If i reproduce the same querry in the new verision of pxweb I get an errror:

```
library(pxweb) # new version
pxweb_query_list <-
    list("Region"=c("*"),
         "Civilstand"=c("*"),
         "Alder"=c("*"),
         "Kon"=c("*"),
         "ContentsCode"=c("BE0101N1"),
         "Tid"=c("2017"))

# Download data
px_data <-
    pxweb_get(url = "http://api.scb.se/OV0104/v1/doris/sv/ssd/BE/BE0101/BE0101A/BefolkningNy",
              query = pxweb_query_list)


# Convert to data.frame
as.data.frame(px_data, column.name.type = "text", variable.value.type = "text")
```
Output:
Downloading large query (in 3 batches):
0%Error in pxweb_advanced_get(url = url, query = query, verbose = verbose) :
 Forbidden (HTTP 403).

The same code works if I only select one municipality and no batching is needed:

```
library(pxweb) # new version
pxweb_query_list <-
    list("Region"=c("1280"),
         "Civilstand"=c("*"),
         "Alder"=c("*"),
         "Kon"=c("*"),
         "ContentsCode"=c("BE0101N1"),
         "Tid"=c("2017"))

# Download data
px_data <-
    pxweb_get(url = "http://api.scb.se/OV0104/v1/doris/sv/ssd/BE/BE0101/BE0101A/BefolkningNy",
              query = pxweb_query_list)


# Convert to data.frame
as.data.frame(px_data, column.name.type = "text", variable.value.type = "text")
```
Output:

> as.data.frame(px_data, column.name.type = "text", variable.value.type = "text")
    region      civilstånd        ålder     kön   år Folkmängd
1    Malmö          ogifta         0 år     män 2017      2610
2    Malmö          ogifta         0 år kvinnor 2017      2452
3    Malmö          ogifta         1 år     män 2017      2481

OS: Windows 10, R 3.4.4, RStudio 1.2.1114. All packages updated to newest versions from CRAN 2019-01-04
EDIT: I'm realised that I'm using Microsoft R Open 3.4.4, not standard R. Maybe that has something to do with the problem?

**Comment by MansMeg** [comment]
Well spotted. This is actually a bug in SCB:s API. They have two API limits, one public that is 110 000 that the pxweb is using and an "informal/internal" limit that is 100 000. The new pxweb package computes optimal chunk size to optimize bandwidth use, that is the reason why the old version works (it is less optimal). SCB has said that they will fix it. And, yes, it is very annoying. Please send them an e-mail and complain. =)

A work-around is to set the parameter explicitly:
```
scb_pxweb <- pxweb("http://api.scb.se/OV0104/v1/doris/sv/ssd/BE/BE0101/BE0101A/BefolkningNy")
scb_pxweb$config$max_values_to_download <- 100000
px_data <-
  pxweb_get(scb_pxweb,
            query = pxweb_query_list)
```
This works for me. I leave this issue open until SCB fix this bug.

**Comment by christianlindell** [comment]
Thanks! I will send SCB an email and complain. This is annoying.

**Comment by MansMeg** [comment]
Great, let me know what they say.

**Comment by magnusmki** [comment]
Thank you for the package update and the work-around tip you mentioned above. The value of max_values_to_download is set to 1000 by default for my API of interest, so I don't understand what my problem is. See code below.

`require(pxweb)
u <- 'http://px.hagstofa.is/pxis/api/v1/is'
pxw <- pxweb(u)
pxw

# Choose (large) px-table
pxw$url$path <- paste(pxw$url$path, "/Efnahagur/utanrikisverslun/1_voruvidskipti/03_inntollskra/UTA03801.px", sep = '' )

# Get (Set) limit to download
pxw$config$max_values_to_download # <- 1000

# Retrieve px-table metadata
px_meta <- pxweb_get(pxw)

# Build a large query
dims <- list("Tollskrárnúmer" = c("*"),
             "Land" = c("*"),
             "Mánuður" = c("*"),
             "Eining" = c("*"))

pxq1 <- pxweb_query(dims)
pxq1
pxq2 <- pxweb_query_as_json(pxq1)
pxq2

# Fetch data (this throws "Error: Too large query in variables: Tollskrárnúmer, Mánuður, Eining")
pxd <- pxweb_get(pxw, pxq1)`


Session info and package version:
`> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Icelandic_Iceland.1252  LC_CTYPE=Icelandic_Iceland.1252    LC_MONETARY=Icelandic_Iceland.1252
[4] LC_NUMERIC=C                       LC_TIME=Icelandic_Iceland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pxweb_0.9.1

loaded via a namespace (and not attached):
 [1] httr_1.4.0      compiler_3.5.2  backports_1.1.3 R6_2.3.0        tools_3.5.2     yaml_2.2.0      curl_3.3       
 [8] Rcpp_1.0.0      xml2_1.2.0      checkmate_1.9.1 jsonlite_1.6   
> 
> 
> packageVersion("pxweb")
[1] ‘0.9.1’`

**Comment by MansMeg** [comment]
Hi!

Thank you for this. This should not happen, and I should try to fix it later on. The reason is that one of the variables: ``Tollskrárnúmer`` is to big (4000 values) while the API limit is just 1000. Currently, this situation is not handled (it is strange that API provider has more values than they will let you download - so please contact them and point to your problem. They should at least have a limit of 5000 if they supply this data.). 

The easiest work-around is to split this into 5 separate queries for different ``Tollskrárnúmer``. Then it should work, but it will not be beautiful. 

But, you should probably also think about your query of other reasons. If you download all this data, it will take 
```
> (5000*250*50*4) / (30*60*60*1000)
[1] 2.314815
```
hours to download.

**Comment by magnusmki** [comment]
Thank you for the prompt reply. I contacted the API provider, and they've changed the API limit to 10.000 max values to download, but the results are still the same. I wonder what might be the issue.

`library(pxweb)

u <- "http://px.hagstofa.is/pxis/api/v1/is/Efnahagur/utanrikisverslun/1_voruvidskipti/03_inntollskra/UTA03801.px"
h <- pxweb(u)

h$config$max_values_to_download # <- is now 10.000 values per call by default

meta <- pxweb_get(h)
vars <- meta$variables

pxweb_query_list <- list("Tollskrárnúmer" = c("*"), # length(vars[[1]]$values) is equal to 4474
                         "Land" = c("*"),           # length(vars[[2]]$values) is equal to 249
                         "Mánuður" = c("*"),        # length(vars[[3]]$values) is equal to 36
                         "Eining" = c("*"))         # length(vars[[4]]$values) is equal to 4

pxq <- pxweb_query(pxweb_query_list)

dat <- pxweb_get(h, pxq)
`

**Comment by MansMeg** [comment]
Hmmm. What is the error message?

**Comment by magnusmki** [comment]
> Hmmm. What is the error message?

```
> library(pxweb)
pxweb: R tools for PX-WEB API.
Copyright (C) 2014-2018 Mans Magnusson, Leo Lahti et al.
https://github.com/ropengov/pxweb

> u <- "http://px.hagstofa.is/pxis/api/v1/is/Efnahagur/utanrikisverslun/1_voruvidskipti/03_inntollskra/UTA03801.px"
> h <- pxweb(u)
> h$config$max_values_to_download # <- is now 10.000 values per call by default
[1] 10000
> meta <- pxweb_get(h)
> vars <- meta$variables
> pxweb_query_list <- list("Tollskrárnúmer" = c("*"), # length(vars[[1]]$values) is equal to 4474
+                          "Land" = c("*"),           # length(vars[[2]]$values) is equal to 249
+                          "Mánuður" = c("*"),        # length(vars[[3]]$values) is equal to 36
+                          "Eining" = c("*"))         # length(vars[[4]]$values) is equal to 4
> pxq <- pxweb_query(pxweb_query_list)
> dat <- pxweb_get(h, pxq)
Error: Too large query in variables: Tollskrárnúmer, Mánuður, Eining
```

**Comment by MansMeg** [comment]
Strange. My guess that this is bug then... But I need to check this to be able to see exactly how difficult it is to fix. Do you have a workaround that work?

**Comment by MansMeg** [comment]
I now added this as a bug in the test suite. This is very likely a bug in the pxweb package. Sorry for this. I will probably not be able to fix this the next couple of days though.

**Comment by MansMeg** [comment]
Alright. Now I found the bug. It is due to a limitation in the current version of the PXWEB API that limits how the package can split up the variables. I've now got multiple questions on the same issue so I wrote a short description of the problem, together with a workaround. You can find it here:
https://github.com/rOpenGov/pxweb/blob/master/TROUBLESHOOTING.md

**Comment by MansMeg** [comment]
Add the Trouble-shooting document to the known issues in the vignette and the README.
