### ISSUE TITLE
Error in pxweb_get() for split query

### ISSUE THREAD

**Issue by haaneshi** [rOpenGov/pxweb#178]
I'm trying to download data from the SCB API. The code works fine when downloading a small subset of the data, but when I want the complete data set (where pxweb tries to split the request) I get the following error: 
Error in permutations(n = n, v = x, r = n) : bad value of n

# The code 

```
# Works fine
url <- "http://api.scb.se/OV0104/v1/doris/sv/ssd/START/PR/PR0301/PR0301J/EXPIM15"

query_list_small <- list(
                   "ContentsCode" = c("000001I4"),
                   "Tid" = c('1990M03'),
                   "SPIN2015" = c('*')
                    )

dat <- pxweb_get(url = url, 
                 query = query_list_small)

```
```
# Fails
url <- "http://api.scb.se/OV0104/v1/doris/sv/ssd/START/PR/PR0301/PR0301J/EXPIM15"

query_list_large <- list(
                   "ContentsCode" = c("000001I4"),
                   "Tid" = c('*'),
                   "SPIN2015" = c('*')
                    )

dat <- pxweb_get(url = url, 
                 query = query_list_large)

```
# Session and package version
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pxweb_0.9.1

loaded via a namespace (and not attached):
[1] httr_1.4.0      compiler_3.5.2  backports_1.1.3 R6_2.3.0        tools_3.5.2     curl_3.3       
[7] yaml_2.2.0      checkmate_1.9.1 jsonlite_1.6   

> packageVersion('pxweb')
[1] ‘0.9.1’

**Comment by MansMeg** [comment]
Strange. I get another error message:
```
Error in pxweb_advanced_get(url = url, query = query, verbose = verbose) : 
  Forbidden (HTTP 403). 
```

**Comment by MansMeg** [comment]
Could you try to install the latest version by:
```
install.packages("devtools")
devtools::install_github("rOpenGov/pxweb")
```
and then see if you get the same error as I do?

**Comment by MansMeg** [comment]
Yes. It is the same bug as in #168 . This worked for me:
```
> scb_pxweb <- pxweb(url)
> scb_pxweb$config$max_values_to_download <- 100000
> px_data <-
+   pxweb_get(scb_pxweb,
+             query = query_list_large)
  Downloading large query (in 2 batches):
  |======================================================================================| 100%
```
If you get it to work this way, please complain to Statistics Sweden. They have known this problem for several months now, but not fixed it.

**Comment by haaneshi** [comment]
That's it! I updated to:

```
> packageVersion("pxweb")
 [1] ‘0.9.14’
```

and I got the same error message:

```
Error in pxweb_advanced_get(url = url, query = query, verbose = verbose) : 
  Forbidden (HTTP 403).

```

Finally, your solution to #168 works for me too!

Thank you! I will write to Statistics Sweden about it.

**Comment by MansMeg** [comment]
Great. I should update CRAN version asap. Thanks for your contribution @haaneshi !
