### ISSUE TITLE
Region filtering in stat Norway not working

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/pxweb#179]
That is,  using pxweb to download data from "http://data.ssb.no/api/v0/en/table/04861" with the query below produce other results. The filtering of Region is not working …

{

  "query": [

    {

      "code": "Region",

      "selection": {

        "filter": "all",

        "values": ["039*"]

      }

    },

    {

      "code": "ContentsCode",

      "selection": {

        "filter": "all",

        "values": ["*"]

      }

    },

    {

      "code": "Tid",

      "selection": {

        "filter": "top",

        "values": ["2"]

      }

    }

  ],

  "response": {

    "format": "json-stat"

  }

}

**Comment by olangsrud** [comment]
Here is the underlying code. Below df2 contains a small data frame correctly filtered, but not df1.

    url <- "http://data.ssb.no/api/v0/en/table/04861"
    query <- ApiData(urlSSB, Region = list("039*"), 
                     ContentsCode = TRUE, Tid = 2i, returnApiQuery = TRUE)
    x_pxweb <- pxweb_get(url = url, query = query)
    df1 <- rjstat::fromJSONstat(x_pxweb)

    x_httr <-  httr::content(httr::POST(url, body = query, encode = "json"), "text")
    df2 <- rjstat::fromJSONstat(x_httr)

**Comment by MansMeg** [comment]
Good, then I can put this as a test case in the package as well.

**Comment by MansMeg** [comment]
This has now been fixed. Thanks for noting it.
