### ISSUE TITLE
City of Helsinki as data source

### ISSUE THREAD

**Issue by muuankarski** [rOpenGov/pxweb#184]
Consider implementing this:

http://api.aluesarjat.fi/PXWeb/pxweb/fi/Helsingin%20seudun%20tilastot/?rxid=47d7de97-7eaf-492c-8f7a-31f9fc360830

**Comment by MansMeg** [comment]
Sure! Otherwise you could just add it yourself and do a PR, then it will be done faster.

**Comment by muuankarski** [comment]
Will do that

**Comment by MansMeg** [comment]
Now included in master.
