### ISSUE TITLE
Outdated URLs

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/pxweb#187]
Running R CMD check --as-cran gives the following:

Found the following (possibly) invalid URLs:
  URL: http://www.scb.se/Grupp/OmSCB/API/API-description.pdf (moved to https://www.scb.se/Grupp/OmSCB/API/API-description.pdf)
    From: inst/doc/pxweb.html
    Status: 404
    Message: Not Found
  URL: http://www.scb.se/sv_/PC-Axis/Programs/PX-Web/PX-Web-examples/ (moved to https://www.scb.se/sv_/PC-Axis/Programs/PX-Web/PX-Web-examples/)
    From: inst/doc/pxweb.html
    Status: 404
    Message: Not Found
  URL: https://www.scb.se/sv_/PC-Axis/Programs/PX-Web/
    From: man/pxweb-package.Rd
    Status: 404
    Message: Not Found

**Comment by MansMeg** [comment]
Fixed.
