### ISSUE TITLE
Returns a list instead of a data frame

### ISSUE THREAD

**Issue by richardohrvall** [rOpenGov/pxweb#191]
Hi!

When I use the interactive mode, as described in the vignette, and select a table from Statistics Sweden's API and that I want it downloaded as a data frame, I get a list instead of a data frame. In the list the data frame is included as an element, so it's easy to extract, but I assume that is not how it's supposed to work.

**Comment by MansMeg** [comment]
What specific part of the vignette give this problem? Could you give a reproducible example?

**Comment by MansMeg** [comment]
I now checked this, and it should actually return it like it does. I tried to clarify it in the documentation now. Thanks for the pointer Richard!
