### ISSUE TITLE
MAP keyword?

### ISSUE THREAD

**Issue by statgreen** [rOpenGov/pxweb#198]
Can pxweb push through the MAP keyword?

I have added MAP to this file:

https://betabank20.stat.gl:443/sq/a317e873-fa82-460f-ad99-fcf7ee28901a.px

**Comment by MansMeg** [comment]
I do not really know what that is? Can you enlight me or send a link?

**Comment by statgreen** [comment]
In the PCAxis format there is very little information:

https://www.scb.se/globalassets/vara-tjanster/px-programmen/pc-axis_fileformat-2008.pdf

MAP
Used for a geographic variable for which maps can be made (new text length 2008). Example:
MAP("region")="Sweden_municipality";


MAP 

So in the file I linked to in last message I have:

CODES("municipality")="00GRL","955","956","957","959","960","961";
MAP("municipality")="Greenland_municipality";


This tells me that the variable 'municipality' has the role a geographic dimension. Also that I can use the codes from that variable together with a map named Greenland_municipality

**Comment by MansMeg** [comment]
So how would you like to use the pxweb R package with that URL? Currently, no PCAXIS files are handled (only JSON)?

pxweb_get("https://betabank20.stat.gl:443/sq/a317e873-fa82-460f-ad99-fcf7ee28901a.px")
?

**Comment by statgreen** [comment]
I'll be back - just need to check something first - might take a week

**Comment by MansMeg** [comment]
Alright. Ill close this issue for now. Reopen it if you still have a problem.
