### ISSUE TITLE
Bad permutation on n

### ISSUE THREAD

**Issue by Mankargren** [rOpenGov/pxweb#201]
Hi!

When I'm getting data from Iceland statistics, in english, I get an error message `"Error in permutations(n = n, v = x, r = n) : bad value of n"`

I think there might be an issue with elimination = FALSE for all variables in the table I'm extracting data from. 
I'm not sure what to do about this. 

Here is some code to reproduce the error:
```
pxweb_query_list <- 
  list("Ríkisfang"=c("*"),
       "Aldur"=c("*"),
       "Ár"=c("*"),
       "Kyn"=c("*"))

# Download data 
px_data <- 
  pxweb_get(url = "http://px.hagstofa.is/pxen/api/v1/en/Ibuar/mannfjoldi/3_bakgrunnur/Rikisfang/MAN04103.px",
            query = pxweb_query_list)
```

Here is my session info:
```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252   
[3] LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                   
[5] LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pxweb_0.9.1

loaded via a namespace (and not attached):
 [1] httr_1.4.1      compiler_3.6.2  backports_1.1.5 R6_2.4.1        tools_3.6.2    
 [6] curl_4.3        Rcpp_1.0.3      xml2_1.2.2      checkmate_1.9.4 jsonlite_1.6.1 

```

Thanks for a very useful package!

**Comment by MansMeg** [comment]
Thanks! Ill look into it asap.

**Comment by MansMeg** [comment]
Hi!

I get:
```
No encoding supplied: defaulting to UTF-8.
 Error: 
This is not a PXWEB API: 
http://px.hagstofa.is/pxen/api/v1/en/Ibuar/mannfjoldi/3_bakgrunnur/Rikisfang/MAN04103.px
```

Could you try with the development version of pxweb? I.e. 10.1 with:
```
library(devtools)
install_github('ropengov/pxweb')
```

**Comment by MansMeg** [comment]
It seems like statistics Iceland has changed their API somehow?

**Comment by Mankargren** [comment]
Hi!
I get the same error as you now - which is not the same i got yesterday. 

However, I get the same error message when I try to access Statistics Icelands database through `pxweb_interactive()`.
Also, as of this morning, their database seems to have a problem:
http://px.hagstofa.is/pxen/

So perhaps this error is an unfortunate coincidence?

**Comment by MansMeg** [comment]
Yes. It seems like there is some problem with their whole API? I sent them an e-mail.

**Comment by Mankargren** [comment]
The Icelandic database is up and running now. 
With the development version om pxweb i instead get the error. 

`Error: Too large query. Variable(s) Ríkisfang, Aldur, Kyn cannot be split into batches (eliminate is FALSE).`

This is a very large query, but I can't access is even if I specify only one year:

```
pxweb_query_list <- 
  list("Ríkisfang"=c("*"),
       "Aldur"=c("*"),
       "Ár"=c("2019"),
       "Kyn"=c("*"))

# Download data 
px_data <- 
  pxweb_get(url = "http://px.hagstofa.is/pxen/api/v1/en/Ibuar/mannfjoldi/3_bakgrunnur/Rikisfang/MAN04103.px",
            query = pxweb_query_list)
```
This worked with the old function `get_pxweb_data()`, which is now defunct.

Is there a workaround on this?

**Comment by MansMeg** [comment]
Hi!

Yes, this is strange. I need to look into it.

/Måns

**Comment by MansMeg** [comment]
I just realized this is a well known problem and I already have a workaround. I have now clarified the error message to be:

```
Error: 
Too large query. 
Variable(s) 'Ríkisfang', 'Aldur', 'Kyn' cannot be split into batches (eliminate is set to FALSE by the API). 
The smallest batch size is 12558 and the maximum number of values that can be downloaded through the API is 10000. 
For details and workarounds, see:
https://github.com/rOpenGov/pxweb/blob/master/TROUBLESHOOTING.md
```

Please reopen this issue if this doesn't solve your problem.

Thanks for opening this issue!
