### ISSUE TITLE
National Statistics Taiwan

### ISSUE THREAD

**Issue by dbescond** [rOpenGov/pxweb#206]
could we add this agency to the catalog:

http://statdb.dgbas.gov.tw/pxweb/dialog/..%5CDialog%5Cvarval.asp?ma=LM0102A1A&ti=Labor%20Force%20by%205%20Ages-Annual&path=../PXfileE/LaborForce/&lang=1&strList=L

http://statdb.dgbas.gov.tw

**Comment by MansMeg** [comment]
Sure! Please just add it to:
https://github.com/rOpenGov/pxweb/blob/master/inst/extdata/api.json
and do a PR to the development branch.

Let me know if you need help with this.

**Comment by dbescond** [comment]
not sure to understand pxweb translation setting from this kind of path:
http://statdb.dgbas.gov.tw/pxweb/Dialog/varval.asp?ma=LM0102A1A&path=../PXfileE/LaborForce/&lang=1
lang 1 = eng
version unknow 
http://statdb.dgbas.gov.tw

could you help plse 


    "statdb.dgbas.gov.tw": {
        "alias" : ["stattw"],
        "description" : "Statistics Taiwan, china",
        "citation" : {
          "organization" : "Statistics Taiwan, china",
          "address" : "Helsinki, Finland"},
        "url" : "http://statdb.dgbas.gov.tw/pxweb/[version]/[lang]",
        "version": ["v1"], 
        "lang": ["1"],
        "calls_per_period": 30,
        "period_in_seconds": 10,
        "max_values_to_download" : 150000
              },

**Comment by MansMeg** [comment]
Ok. So that is a path to the web based PXWEB. You need the path to the API. You should probably ask the Taiwanese statistical agency. It might be so that they have not made the API available.

**Comment by dbescond** [comment]
well we have to wait, this is answer from Taiwan Statistics:

We would like to thank you for your letter inquiring about our DGBAS services.
The DGBAS was setted up on the basic functions of PC-AXIS 2008.
Due to the PC-AXIS 2008 do not provide the API link, the API link of DGBAS is invalid. 
In addition, the DGBAS's PxWeb function did not be upgraded to the latest version, because some chinese characters cannot be displayed correctly in the PxWeb query system.

However, we are trying to rebuild a new DGBAS database in the near future.
The support of API link should be included into our proposal.
Thanks for your great recommendations.

so pending development

**Comment by MansMeg** [comment]
Thanks!
