### ISSUE TITLE
Travis-CI to GitHub Actions

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/pxweb#211]
Old Travis-CI.org service will be shut down after 31th of December, requiring either action to migrate to the commercial Travis-CI.com service or migrating to a new CI altogether. [An rOpenSci blogpost](https://ropensci.org/technotes/2020/11/19/moving-away-travis/) describes the pros of moving to GitHub Actions. The process is as follows:

1. run: `usethis::use_github_action_check_standard()`
2. Check if package tests contain skip_on_travis -functions and replace them with skip_on_ci 
3. Add a badge to the package README: `[![R build status](https://github.com/rOpenGov/PACKAGENAME/workflows/R-CMD-check/badge.svg)](https://github.com/rOpenGov/PACKAGENAME/actions)`
4. Remove Travis CI badge (and Appveyor badge as well, since GHA runs tests simultaneously for Linux, macOS and Windows)

**Comment by antagomir** [comment]
Is ok. Remember to remove .travis and appveyor.yml files from root folder too.

And in tests skip_on_travis should be replaced with skip_on_ci

Can you make a PR?

**Comment by antagomir** [comment]
@MansMeg I have checked and tested this, it is all OK and should be actually done, so Pyry will make a PR soon

**Comment by MansMeg** [comment]
Great!

It seem to be a failing test case. Lets check that before we merge. We also need to change the badges.
