### ISSUE TITLE
Getting everything without specifying variables

### ISSUE THREAD

**Issue by ankargren** [rOpenGov/pxweb#222]
Brief summary: `pxweb` always requires mandatory variables to be given in queries, but that's not needed using e.g. `httr::POST()`. Is there a reason for this, or could this be implemented?

Some more information: A manual query in the Statistics Sweden's Statistical database is accompanied by a JSON string. Here's one such search where I simply selected all sectors, all items, all quarters: [https://www.statistikdatabasen.scb.se/sq/110177](https://www.statistikdatabasen.scb.se/sq/110177). At the bottom is the URL and JSON string for the query:

```
http://api.scb.se/OV0104/v1/doris/en/ssd/START/NR/NR0108/FirBruttoKonvKv

{
  "query": [],
  "response": {
    "format": "px"
  }
}

```
If I use this URL and JSON in `pxweb`, the query errors because I didn't specify mandatory variables:

```
Error: Mandatory variable(s) 'Sektor', 'Kontopost', 'ContentsCode', 'Tid' is missing in the query.
```
but works fine if I use `httr::POST()`. So using `httr::POST()`, whatever variables I did not specify any selections for I automatically get everything for. It would be great if `pxweb` would work the same way, especially since currently the JSON strings provided automatically by Statistics Sweden cannot be used with `pxweb` if the request was to get everything.

Here's some code to illustrate differences:

```
library(pxweb)
url <- "http://api.scb.se/OV0104/v1/doris/en/ssd/START/NR/NR0108/FirBruttoKonvKv"
query1 <- '{
  "query": [],
  "response": {
    "format": "px"
  }
}'



px1 <- pxweb_get(url, query1)         # Does not work
px2 <- httr::POST(url, body = query1) # Does work


# More elaborate query with wildcard searches for all variables specified
query2 <- '{
  "query": [
    {
      "code": "Sektor",
      "selection": {
        "filter": "all",
        "values": [
          "*"
        ]
      }
    },
    {
      "code": "Kontopost",
      "selection": {
        "filter": "all",
        "values": [
          "*"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "all",
        "values": [
          "*"
        ]
      }
    },
    {
      "code": "ContentsCode",
      "selection": {
        "filter": "all",
        "values": [
          "*"
        ]
      }
    }
  ],
  "response": {
    "format": "px"
  }
}'


# Now both work
px3 <- pxweb_get(url, query2)
px4 <- httr::POST(url, body = query2)

```

Let me know if you want any more details or information, or (even better) if I missed some existing solution for this issue!

**Comment by MansMeg** [comment]
Thanks for reporting!

I think this should be something that could be implemented relatively easy. As you say it should be good to be able to use an empty JSON as a call. The easiest would be to just assume ”take all” values for missing variables.

Although, Im not sure how quickly I can fix this.

**Comment by ankargren** [comment]
I made a quick attempt, I'm thinking that one approach is to add a function like `pxweb_add_mandatory_variables(url, query` immediately after line 98 in `pxweb_get.R`, i.e. following `pxq <- pxweb_query(query)`. Then we can expect `pxw` to be a JSON-type list, so we'd only need something like:

```
pxq <- pxweb_query(query)
pxq <- pxweb_add_mandatory_variables(url, pxq)
```
and mandatory variables would be added to the request with wildcards. 

Here's an example of what the function could look like with examples:

```
query1 <- '{
  "query": [],
  "response": {
    "format": "px"
  }
}'

query2 <- '{
  "query": [
    {
      "code": "Sektor",
      "selection": {
        "filter": "all",
        "values": [
          "*"
        ]
      }
    },
    {
      "code": "Kontopost",
      "selection": {
        "filter": "all",
        "values": [
          "*"
        ]
      }
    }],
  "response": {
    "format": "px"
  }
}'

query1 <- pxweb_query(query1)
query2 <- pxweb_query(query2)

pxweb_add_mandatory_variables <- function(url, query) {
  px <- pxweb(url)
  metadata <- pxweb_get(px)
  mandatory_variables <- vapply(metadata$variables, function(x) x$code, character(1))
  provided_variables <- vapply(query$query, function(x) x$code, character(1))
  missing_mandatory_variables <- setdiff(mandatory_variables, provided_variables)
  
  select_everything_template <- function(x) {
    list(code = x,
         selection = list(filter = "all",
                          values = "*"))
  }
  
  query_appendix <- lapply(missing_mandatory_variables, select_everything_template)
  query$query <- append(query$query, query_appendix)
  return(query)
}

url <- "http://api.scb.se/OV0104/v1/doris/en/ssd/START/NR/NR0108/FirBruttoKonvKv"
query1 <- pxweb_add_mandatory_variables(url, query1)
query2 <- pxweb_add_mandatory_variables(url, query2)
pxd1 <- pxweb_get(url, query1)
pxd2 <- pxweb_get(url, query2)
all.equal(as.data.frame(pxd1), as.data.frame(pxd2))
```

I don't know if there are other parts of the package that also needs to change as I don't know it well enough. But in any case maybe this is a start.

**Comment by MansMeg** [comment]
This looks great! That was actually how I would have implemented it, because this should also enable calls without JSON to be specified without all variables. I would though have added a message that if it adds these variables, it also spit out a message that ”variable x is missing, all elements are included” or similar.

I think you have everything needed to put together a pull request with this fix. It would be very appreciated. I can help you by reviewing your PR.

**Comment by MansMeg** [comment]
Oh yes. I would also put that function in the pxweb_get/pxweb_advanced_get so it is done automatically.

**Comment by ankargren** [comment]
Great! I’ve put it into the package (including a message) but having some problems with existing tests not passing, but should be ready soon.

**Comment by MansMeg** [comment]
Cool! There can be some issues not related to your contribution. It might be that some API has changed. 

If you do a PR tests are run and we can help each other out trying to identify the problems.

**Comment by MansMeg** [comment]
Now included. I need to handle eliminated variables so I solved this by casting a warning if needed to include all variables. Please feel free to try version 0.11 out.

**Comment by MansMeg** [comment]
I realized I should add you as a contributor to the package. Are you ok with that?

**Comment by ankargren** [comment]
Sure, it would be my pleasure!

**Comment by MansMeg** [comment]
Cool!

Ill do it now here. I submitted to CRAN yesterday, but there was a NOTE on a redirect error of a url. So they might want me to fix that. Otherwise you will be part of it next release.
