### ISSUE TITLE
pxweb_interactive gives Error: Incorrect return response from PXWEB API url

### ISSUE THREAD

**Issue by emilwest** [rOpenGov/pxweb#230]
Hi,

When using `pxweb_interactive()` and navigating using the following options:
```
[ 16 ] : Statistics Norway
[ 1 ] : v0  
[ 1 ] : en 
[ 1 ] : Statbank by subject
[ 18 ] : Transport and tourism
[ 3 ] : Tourism 
[ 3 ] : Accommodation 
```

I get the following error returned on the last selection (accommodation):
`Error: Incorrect return response from PXWEB API url: 
http://data.ssb.no/api/v0/en/table/tr/tr04/overnatting`

When retrieving the data like this however, it works as expected:
```r
pxweb_query_list <-
    list("Region"=c("0"),
         "Landkoder2"=c("*"),
         "ContentsCode"=c("Overnattinger"),
         "Tid"=c("*"))

  # Download data
  px_data <-
    pxweb_get(url = "http://data.ssb.no/api/v0/en/table/tr/tr04/overnatting/SBMENU8380/HotellOvernMnd",
              query = pxweb_query_list)
```
 
I'm not sure whether it's a problem with SSB or pxweb, in any case I would be happy to know more about the error!

My specs:
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)
pxweb version: 0.11.0

**Comment by MansMeg** [comment]
Hi! Thanks for reporting! I need to check this manually. I guess the problem is in SSB, but Im not sure.

**Comment by emilwest** [comment]
Thanks for fixing!
