### ISSUE TITLE
PxWeb API from the new PxStat open-data platform

### ISSUE THREAD

**Issue by lorenzobruni** [rOpenGov/pxweb#235]
Hi,
I write from the **CSO (Central Statistics Office, Ireland)** as I had the opportunity to talk to @statgreen from **Statistics Greenland** who presented the beauty of this R project in the last **International PX Conference**.

At the CSO, we have developed a new Open-Data Portal called **PxStat**; simply an alternative to PxWeb but including the data-management and data-creation phases as well. The project is fully API driven, including the interface all Ajax based.
The open-source project is in Github at https://github.com/CSOIreland/PxStat
The Live interface for Ireland, for you to see it in action, is at https://data.cso.ie

#### After this brief introduction, come my question :-)

As the project is fully API driven, PxStat offers 3 different API end-point both over GET and POST verbs:
* A pure **RESTful** implementation for full-download
* A **JSON-RPC** implementation for query selection
* A **PxAPIv1** (aka **PX-WEB API**) for compatibility with PxWeb.

We have developed the PxAPIv1 following the documentation from Statistics Sweden, to build the PX WEB API.
The output generated from our API (apparently) looks the same as the one generated from any PX WEB API, but for some reasons, when trying to run it from your R package, an error is returned informing that the API is not compatible with PX WEB.

#### Can you please help us understanding where the issue is?
Feel free to query any of our datasets at https://data.cso.ie
An example for the table EDA22 (Expenditure on Students): https://data.cso.ie/table/EDA22 

Just make the selection you want, then you find the API section at the bottom, where you select PxAPIv1 and you can use both GET and POST. See screenshot below.
![image](https://user-images.githubusercontent.com/53212047/138862244-3569c98a-0829-4adb-84eb-aab4389bf243.png)

FYI, if it can help, the CSO has also published an R package, that you can find here: https://cran.r-project.org/web/packages/csodata/index.html 

#### I will be very happy if we could query the PxAPIv1 (PX WEB API) from PxStat using this R package!

Thanks a mill.

**Comment by MansMeg** [comment]
As I expected, it seems like your pxweb API does not return the config of the API for the R package to work.

When I call: 
https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/en/41/DOEO/EDA22?config
I just get an ordinary pxweb object rather than the config of the API. 

The R package need the info on "maxValues", "maxCalls", "timeWindow" to be able to divide the larger calls into the right sized chunks to download.

So if you implement the query ?config I hope it should work.

**Comment by MansMeg** [comment]
ping @lorenzobruni

**Comment by lorenzobruni** [comment]
Hi @MansMeg,

thanks a lot for your prompt reply and sorry for my late one but apparently I'm not getting Github notifications anymore, I must review my account settings I guess :-)

I was not aware of the `?config` requirement, good you spot it!
I looked again in the PxApi Specifications but I cannot locate the details of this requirement:
* https://github.com/statisticssweden/PxApiSpecs
* https://www.scb.se/en/services/open-data-api/api-for-the-statistical-database/

Could you please tell me the meaning of each setting below, so we can easily implement it?
I also notice that it returns the same configuration for every table... is that right or just a coincidence?

```json
{
maxValues: 110000,
maxCells: 150000,
maxCalls: 30,
timeWindow: 10,
CORS: true
}
```

Thanks a mill!

**Comment by MansMeg** [comment]
Hi!

It was a part of the API definitions before and all APIs we have been working with have this ?config. I can't find that documentation myself now, but you could probably ask them.

I think the thing you linked is the pxweb version 2.0, which is a different thing that I'm not sure is ready and is up and running? So pxweb now use API version 1.

The config is a general configuration used by the whole API on the number of allowed calls etc. Hence it gives the same result for all tables. The pxweb package use it to handle calls to the API efficiently (especially large calls).

**Comment by lorenzobruni** [comment]
Hi @MansMeg 
Thanks a lot, our good friend @statgreen has kindly provided the documentation with the specs for the `?config` :-)
I will keep you posted once ready for testing.

Have a good day!

**Comment by MansMeg** [comment]
Great! I'll close this issue for now. Feel free to continue the discussion here if you have further questions.
