### ISSUE TITLE
Changes in API: Statistics Finland StatFin database and its interfaces

### ISSUE THREAD

**Issue by pitkant** [rOpenGov/pxweb#238]
Heads-up of an upcoming change:

"The links in Statistics Finland's StatFin database will be renewed on 5.4.2022. The change also affects the use of the interface.

Highlights:

* The database address changes.
before: https://pxnet2.stat.fi/PXWeb/pxweb/en/StatFin/
in the future: https://statfin.stat.fi/PXWeb/pxweb/fi/StatFin/

* Because the database no longer shows the topic level, the combination of letters describing the topic is removed from the table links.
  * The topic identifier can be found in the old links in the second last part of URL before the identifier of the statistics. For example, the identifier of the topic population is vrm and it can be seen in the following link between the texts StatFin and vaerak: 
https://pxnet2.stat.fi/PXWeb/pxweb/en/StatFin/StatFin__vrm__vaerak/statfin_vaerak_pxt_11ra.px/
  * There is no topic identifier in the new table links. The new address of the example table as of 5 April 2022 is as follows: 
https://statfin.stat.fi/PXWeb/pxweb/en/StatFin/StatFin__vaerak/statfin_vaerak_pxt_11ra.px
  * Please note that in the second last part there are two underline characters between the letters StatFin and the identifier of the statistics: StatFin__vaerak

* Saved searches are automatically corrected in Statistics Finland.

* Old links and interface calls work until July, but they lead to a frozen version of the database.

More information: https://stat.fi/ajk/verkkosivu-uudistus/uudistuksen-vaikutukset-statfin-tietokantaan_en.html"

**Comment by MansMeg** [comment]
But will it affect the pxweb web API? It just looks like differences on the website? The pxweb web API has not changed according to my dialogue with the pxweb developers. I get:
```
 Error: 'https://statfin.stat.fi/PXWeb/pxweb/fi/StatFin/' is not a PXWEB API. See pxweb_api_catalogue() for available PXWEB APIs. 
```

**Comment by MansMeg** [comment]
I changed the API-adress to the new path. That apparently will change.

**Comment by pitkant** [comment]
Isn't that "is not a PXWEB API" message printed when the URL is not included in inst/extdata/api.json file? Therefore it would print the message for station.stat.fi since it is not included in the file. And yes, this change should affect API:

"The renewal influences the structure of the StatFin database, publishing of database tables and communicating about tables, browsing of tables and all links in the database. Changing of links has an effect especially on interface (API) use"
