### ISSUE TITLE
Slovenian stats agency not in the catalogue?

### ISSUE THREAD

**Issue by majazaloznik** [rOpenGov/pxweb#241]
I was under the impression that the Slovenian statistical office also uses a PxWeb API - according to their own [documentation ](https://www.stat.si/StatWeb/File/DocSysFile/10722/px_web_api_helpEN.pdf) as well as being listed on the SCB site [here](https://www.scb.se/en/services/statistical-programs-for-px-files/px-web/pxweb-examples/). But they are not listed in the `pxweb_api_catalogue`, how come?

**Comment by MansMeg** [comment]
Because we dont know they use pxweb. :) Please check if you can use the package (for example with pxweb_interactive, using the pxweb url). If it works, feel free to add it or supply the url here and I will add it.

**Comment by majazaloznik** [comment]
Sorry, my apologies, I read the rest of your vignette and managed to get it to work. The only problem is I can only get it to work with this URL: [https://pxweb.stat.si/SiStatData/api/v1/sl/](`https://pxweb.stat.si/SiStatData/api/v1/sl/`). But if I use any of the higher level URLs  I get the following error:

```
Error in assert_pxweb_explorer(x = pxe) : 
  Assertion on 'x$root' failed: Must be a subset of {'SiStatData','api','v1'}, but has additional elements {'NA'}.
```

**Comment by majazaloznik** [comment]
I also don't understand what the difference is between the `Data/` and `PcWin/Data/` paths, they look the same, but it makes no sense they would duplicate everything like that?

**Comment by MansMeg** [comment]
And dont be suprised on what NSI can do with the pxweb API. They do really strange things sometimes.

**Comment by majazaloznik** [comment]
Haha, cheers for the heads up! I've just gotten a contact there so I'll try to dig up some more info. If you have (or can help me formulate) any questions, just let me know.

**Comment by MansMeg** [comment]
I just tried it, and to me it works with:
```
test <- pxweb_interactive("https://pxweb.stat.si/SiStatData/api/v1/sl/")
```
Although when looking under data it seems like all 3000 tables are stored under Data/. This is not very user friendly, so please ask them to create a better structure.

Also, the following gives me the same results as you. It is the response from their API that is strange, so please ask them to fix that.
```
test <- pxweb_interactive("https://pxweb.stat.si/SiStatData/api/")
```

Also, it seems like a really unstable server as of now:
```
> pxwg <- pxweb_get("https://pxweb.stat.si/SiStatData/api/")
Error in pxweb_advanced_get(url = url, query = query, verbose = verbose) : 
  Internal Server Error (HTTP 500).
```

Maybe tell them that as well... =)

**Comment by majazaloznik** [comment]
Why do you say it's unstable? isn't  `pxweb_interactive()` just a wrapper for ` pxweb_get()`? I mean what would you expect to get on the second line?

**Comment by MansMeg** [comment]
Yes. I was mainly refrering to the 500 error code. There seem to be some server problems.

**Comment by majazaloznik** [comment]
OK, I'll let you know what i can find out, cheers!

**Comment by MansMeg** [comment]
In the new release (0.15.1) I updated the API file so this is now part of the package. It's on its way to CRAN.

**Comment by majazaloznik** [comment]
that's amazing, thank you!! 😀
