### ISSUE TITLE
stat2go.com

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/pxweb#85]
Could we add this pxweb API: stat2go.com May require some investigation.

**Comment by eydunn** [comment]
Is it a pxweb site? 
Isn't it 'just' a site that uses the nordic pxweb API's?

**Comment by MansMeg** [comment]
I think so to. But it is good. We can just add the other nordic api:s as well.

**Comment by antagomir** [comment]
Yes perhaps the best solution is to add the other nordic apis separately.

**Comment by MansMeg** [comment]
Have a look if any is missing. Then close.

**Comment by MansMeg** [comment]
I close this now. I think we have most API:s otherwise we just add new ones.
