### ISSUE TITLE
Change to travis R native

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/pxweb#86]
Change package to travis R native.

See:
http://docs.travis-ci.com/user/languages/r/

**Comment by MansMeg** [comment]
@antagomir Can you undo the latest commit (travis now failes) or fix it?

**Comment by MansMeg** [comment]
It still does not work? After updating the travis file no builds has been built?

We also need to check both for NOT_CRAN = true and NOT_CRAN = false. I use the matrix functionality before, I don't knowhow to implement this with R native.

**Comment by antagomir** [comment]
The latest travis build from 43 min ago passes:
https://travis-ci.org/rOpenGov/pxweb So to me it seems everything is ok but
perhaps I am missing something?

I can change the travis script back to earlier version if you like. I made
this as it was listed as an open issue.

Leo

**Comment by MansMeg** [comment]
The problem is that after you updated the travis file, it stoped to run travis builds, so the latest builds has not been checked. If you can get it to work it would be great! 

The latest build commit: 605f2c9af01c74173abc736916739169b1785691
The latest commit: e93b2490fe29a5f577b1d1d1872c70a00545d528

**Comment by antagomir** [comment]
OK, I did not manage to get it working with R yet so returned the old
travis version which now seems to work.

**Comment by MansMeg** [comment]
Cool! We leave this issue open then. =)
