### ISSUE TITLE
Go through the testsuite and check for errors

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/pxweb#89]

**Comment by jhuovari** [comment]
Hi,

I tried to test a little change I made, but got 5 test failures (unrelated to the change). 

Either of two apis were involved in all failures: 
 * http://api.scb.se/OV0104/v1/doris/en/ssd/BE/BE0401/BE0401A/BefolkprognRev2014. Reason: unavailable at the moment. Permanent or temporary?

* http://api.scb.se/OV0104/v1/doris/sv/ssd/ME/ME0104/ME0104C/ME0104T3. 

```
1. Failure(@test-get_pxweb_data.R#137): get_pxweb_data() -----------------------
{
    test_data <- get_pxweb_data(url = test$url, dims = test$dims, clean = test$clean)
} threw an error
http://api.scb.se/OV0104/v1/doris/sv/ssd/ME/ME0104/ME0104C/ME0104T3

2. Failure(@test-get_pxweb_data.R#146): get_pxweb_data() -----------------------
dim(test_data) not equal to test_dim_size
Mean relative difference: 0.978022
http://api.scb.se/OV0104/v1/doris/sv/ssd/ME/ME0104/ME0104C/ME0104T3

3. Failure(@test-get_pxweb_data.R#137): get_pxweb_data() -----------------------
{
    test_data <- get_pxweb_data(url = test$url, dims = test$dims, clean = test$clean)
} threw an error
http://api.scb.se/OV0104/v1/doris/en/ssd/BE/BE0401/BE0401A/BefolkprognRev2014

4. Failure(@test-get_pxweb_data.R#146): get_pxweb_data() -----------------------
dim(test_data) not equal to test_dim_size
Mean relative difference: 63
http://api.scb.se/OV0104/v1/doris/en/ssd/BE/BE0401/BE0401A/BefolkprognRev2014

5. Failure(@test-get_pxweb_metadata.R#45): baseURL 2 ---------------------------
{
    api_test_file <- get_pxweb_metadata(path = test)
} threw an error

```

**Comment by MansMeg** [comment]
Ok. Great. Ill look into it asap. But the first adress serms to work. Strange.

**Comment by MansMeg** [comment]
Do you have the log file? Cant find it on travis? (Im in contact with travis support).

**Comment by jhuovari** [comment]
Do you mean check log file? Here: https://www.dropbox.com/s/pc4lj3lki5znomh/00check.log?dl=0.

For the first address I still get Server error: 404 - File or directory not found. With ending: BefolkprognRev2015 it do work.

The problem with the second address is due to non-ascii character. @test-get_pxweb_data.R#146 there is Ö in Partimm = c('M','C','FP','KD','MP','S','V','SD','ÖVRIGA') and when R CMD check on windows is assuming local non-UTF-8 encoding, it fails.

**Comment by MansMeg** [comment]
Alright! Then I know the problem, thanks. I thought it was a problem with
Travis CI (I've had problems with it before).

**Comment by MansMeg** [comment]
This should now be fixed!
