### ISSUE TITLE
Add new data source

### ISSUE THREAD

**Issue by MansMeg** [rOpenGov/pxweb#92]
https://oppna.helsingborg.se/helsingborgsstatistik-som-oppna-data/

http://statistik.linkoping.se/pxweb2008/Database/Linkoping/Linkoping.asp

**Comment by thelinkan** [comment]
Question: Can only admins from the respective pxweb site request adding the site to the package, or can I add those I find to the json file and do a pull request?

Found another one using api
http://bank.stat.gl/pxweb/en/Greenland

Correct URL for Linköping is
http://statistik.linkoping.se/PXweb/pxweb/sv/

**Comment by MansMeg** [comment]
Hi!

No problem, just add them by sending me a pull request!

You shuold just add them to this api json file.
https://github.com/rOpenGov/pxweb/blob/master/inst/extdata/api.json

/Måns

2015-09-29 16:29 GMT+02:00 Torbjörn Lindquist <notifications@github.com>:

> Question: Can only admins from the respective pxweb site request adding
> the site to the package, or can I add those I find to the json file and do
> a pull request?
>
> Found another one using api
> http://bank.stat.gl/pxweb/en/Greenland
>
> Correct URL for Linköping is
> http://statistik.linkoping.se/PXweb/pxweb/sv/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rOpenGov/pxweb/issues/92#issuecomment-144077493>.
>



-- 
Med vänlig hälsning

Måns

============================
Måns Magnusson
070 - 588 97 15
mons.magnusson@gmail.com
============================

**Comment by thelinkan** [comment]
http://w3.unece.org/pxweb/en/ - Has new enough version, but don't seem to have API activated
http://en.eustat.eus/ci_ci/indice.html - Shows a link to API with wrong URL

**Comment by MansMeg** [comment]
Great!

I sent an email to them and asked them to give access to the API. =) The
second I cant find the API?

/Måns




2015-09-29 20:39 GMT+02:00 Torbjörn Lindquist <notifications@github.com>:

> http://w3.unece.org/pxweb/en/ - Has new enough version, but don't seem to
> have API activated
> http://en.eustat.eus/ci_ci/indice.html - Shows a link to API with wrong
> URL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rOpenGov/pxweb/issues/92#issuecomment-144150727>.
>



-- 
Med vänlig hälsning

Måns

============================
Måns Magnusson
070 - 588 97 15
mons.magnusson@gmail.com
============================

**Comment by thelinkan** [comment]
http://www.eustat.eus/bankupx/pxweb/en/english/ for English PXWeb on EUstat

**Comment by MansMeg** [comment]
Great but do it contain an API?

2015-09-29 20:49 GMT+02:00 Torbjörn Lindquist <notifications@github.com>:

> http://www.eustat.eus/bankupx/pxweb/en/english/ for English PXWeb on
> EUstat
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rOpenGov/pxweb/issues/92#issuecomment-144153804>.
>



-- 
Med vänlig hälsning

Måns

============================
Måns Magnusson
070 - 588 97 15
mons.magnusson@gmail.com
============================

**Comment by MansMeg** [comment]
Yes. Here:
http://net-inter-eustat-45.ejgvdns/bankupx/api/v1/en/english/PX_2212_ep04b.px

2015-09-29 20:54 GMT+02:00 Måns Magnusson <mons.magnusson@gmail.com>:

> Great but do it contain an API?
>
> 2015-09-29 20:49 GMT+02:00 Torbjörn Lindquist <notifications@github.com>:
>
>> http://www.eustat.eus/bankupx/pxweb/en/english/ for English PXWeb on
>> EUstat
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rOpenGov/pxweb/issues/92#issuecomment-144153804>.
>>
>
>
>
> --
> Med vänlig hälsning
>
> Måns
>
> ============================
> Måns Magnusson
> 070 - 588 97 15
> mons.magnusson@gmail.com
> ============================
>



-- 
Med vänlig hälsning

Måns

============================
Måns Magnusson
070 - 588 97 15
mons.magnusson@gmail.com
============================

**Comment by thelinkan** [comment]
When I try to call net-inter-eustat-45.ejgvdns I don't get any response (shouldn't either since it seems to be an internal dns name). 

When calling http://www.eustat.eus/bankupx/api/v1/es/spanish/PX_2212_ep06b.px I get a response, but with content-lenght 0.

**Comment by MansMeg** [comment]
Strange. The API do not seem to work then?

2015-09-29 21:01 GMT+02:00 Torbjörn Lindquist <notifications@github.com>:

> When I try to call net-inter-eustat-45.ejgvdns I don't get any response
> (shouldn't either since it seems to be an internal dns name).
>
> When calling
> http://www.eustat.eus/bankupx/api/v1/es/spanish/PX_2212_ep06b.px I get a
> response, but with content-lenght 0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rOpenGov/pxweb/issues/92#issuecomment-144157213>.
>



-- 
Med vänlig hälsning

Måns

============================
Måns Magnusson
070 - 588 97 15
mons.magnusson@gmail.com
============================

**Comment by thelinkan** [comment]
That is my conclusion as well. My guess is that they have made some customization that clashes with the API.

**Comment by eydunn** [comment]
"Question: Can only admins from the respective pxweb site request adding the site to the package, or can I add those I find to the json file and do a pull request?"

At least inform them and be sure to get all the settings right: Languages, limits etc.

**Comment by MansMeg** [comment]
Thats true! I should include a test that do a shallow test if all apis inbthe catalogue.

**Comment by MansMeg** [comment]
Now I have shallow tests of all apis and more elaborate tests for new apis added to the catalogue.
